import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import {AuthProvider} from "@/app/_components/auth-provider";
import {Separator} from "@/components/ui/separator";
import {Toolbar} from "@/app/_components/toolbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
    >

    <AuthProvider>
      <Toolbar/>
      <Separator/>
      <div
        className='grid grow grid-rows-[20px_1fr_20px] items-center justify-items-center gap-16 p-8 pb-20 font-[family-name:var(--font-geist-sans)] sm:p-20'>
        <main
          className='row-start-2 flex flex-col items-center gap-[32px] sm:items-start'>
          {children}
        </main>
        <Toaster/>
      </div>
    </AuthProvider>
    </body>
    </html>
  );
}
